// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FhirNexusShaun.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "Environment:Integration")]
    public partial class EducationFeature : object, Xunit.IClassFixture<EducationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Environment:Integration"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "education.feature"
#line hidden
        
        public EducationFeature(EducationFeature.FixtureData fixtureData, FhirNexusShaun_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Education", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "HeaderName",
                        "Value"});
            table28.AddRow(new string[] {
                        "X-Ihis-SourceApplication",
                        "testapp"});
#line 5
    testRunner.And("a new HttpClient as httpClient", ((string)(null)), table28, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reading a newly created education resource returns exactly the same education")]
        [Xunit.TraitAttribute("FeatureTitle", "Education")]
        [Xunit.TraitAttribute("Description", "Reading a newly created education resource returns exactly the same education")]
        public void ReadingANewlyCreatedEducationResourceReturnsExactlyTheSameEducation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reading a newly created education resource returns exactly the same education", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 10
    testRunner.Given("a Resource is created from Samples/Education.json as createdEdu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
    testRunner.When("getting Education/{createdEdu.Id} as readEdu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
    testRunner.Then("createdEdu and readEdu are exactly the same", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reading a nonexistent education returns 404 status code")]
        [Xunit.TraitAttribute("FeatureTitle", "Education")]
        [Xunit.TraitAttribute("Description", "Reading a nonexistent education returns 404 status code")]
        public void ReadingANonexistentEducationReturns404StatusCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reading a nonexistent education returns 404 status code", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 15
    testRunner.When("getting Education/{newguid} as readEdu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Path",
                            "Value"});
                table29.AddRow(new string[] {
                            "statusCode",
                            "404"});
#line 16
    testRunner.Then("readEdu is a Fhir OperationOutcome with data", ((string)(null)), table29, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Updating a newly created education resource returns an education with an incremen" +
            "ted versionId")]
        [Xunit.TraitAttribute("FeatureTitle", "Education")]
        [Xunit.TraitAttribute("Description", "Updating a newly created education resource returns an education with an incremen" +
            "ted versionId")]
        public void UpdatingANewlyCreatedEducationResourceReturnsAnEducationWithAnIncrementedVersionId()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Updating a newly created education resource returns an education with an incremen" +
                    "ted versionId", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 21
    testRunner.Given("a Resource is created from Samples/Education.json as createdEdu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Path",
                            "Value",
                            "FhirType"});
                table30.AddRow(new string[] {
                            "study",
                            "Geology",
                            "string"});
#line 22
    testRunner.When("updating createdEdu with data as updatedEdu", ((string)(null)), table30, "When ");
#line hidden
#line 25
    testRunner.And("getting Education/{createdEdu.Id}/_history/2 as readUpdatedEdu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
    testRunner.Then("updatedEdu and readUpdatedEdu are exactly the same", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "Path",
                            "Value"});
                table31.AddRow(new string[] {
                            "statusCode",
                            "200"});
                table31.AddRow(new string[] {
                            "headers.eTag",
                            "W/\"2\""});
#line 27
    testRunner.And("updatedEdu is a Fhir Education with data", ((string)(null)), table31, "And ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "Path",
                            "Value",
                            "FhirType"});
                table32.AddRow(new string[] {
                            "study",
                            "Geology",
                            "string"});
                table32.AddRow(new string[] {
                            "meta.versionId",
                            "2",
                            "string"});
#line 31
    testRunner.And("readUpdatedEdu is a Fhir Education with data", ((string)(null)), table32, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Updating an education resource with a mismatch of id in the body and path returns" +
            " 400 status code")]
        [Xunit.TraitAttribute("FeatureTitle", "Education")]
        [Xunit.TraitAttribute("Description", "Updating an education resource with a mismatch of id in the body and path returns" +
            " 400 status code")]
        public void UpdatingAnEducationResourceWithAMismatchOfIdInTheBodyAndPathReturns400StatusCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Updating an education resource with a mismatch of id in the body and path returns" +
                    " 400 status code", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 37
    testRunner.Given("a Resource is created from Samples/Education.json as createdEdu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "Path",
                            "Value",
                            "FhirType"});
                table33.AddRow(new string[] {
                            "study",
                            "Geology",
                            "string"});
                table33.AddRow(new string[] {
                            "id",
                            "{newguid}",
                            "id"});
#line 38
    testRunner.When("updating createdEdu with data as updatedEdu", ((string)(null)), table33, "When ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "Path",
                            "Value",
                            "FhirType"});
                table34.AddRow(new string[] {
                            "statusCode",
                            "400",
                            ""});
                table34.AddRow(new string[] {
                            "issue[0].diagnostics",
                            "Resource ID in resource does not match with Resource ID in path.",
                            "string"});
#line 42
    testRunner.Then("updatedEdu is a Fhir OperationOutcome with data", ((string)(null)), table34, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                EducationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                EducationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
